### ISSUE TITLE
Request: Upasargarthachandrika

### ISSUE THREAD

**Issue by suhasm** [indic-dict/stardict-sanskrit-vyAkaraNa#16] opened 2023-02-19 22:23 UTC
Please make the headwords contain the upsargasanghāta+ dhātu
I mean: praṇidhā should be a headword, not just praṇi

**Comment by vvasuki** [comment] 2023-02-20 02:09
Duplicate of https://github.com/indic-dict/stardict-sanskrit/issues/166 . Following up there.

**Closed as completed by vvasuki** 2023-02-20 02:09 UTC
